export const colourOptions = [
    { value: "Swimming", label: "Swimming", color: "#00B8D9" },
    { value: "MountainClimbing", label: "Mountain Climbing", color: "#0052CC" },
    { value: "Reading", label: "Reading", color: "#5243AA" },
    { value: "Coding", label: "Coding", color: "#FF5630" },
    { value: "Painting", label: "Painting", color: "#FF8B00" },
    { value: "Sewing", label: "Sewing", color: "#FFC400" },
    { value: "Biking", label: "Biking", color: "#36B37E" },
    { value: "Running", label: "Running", color: "#00875A" },
    { value: "WorkingOut", label: "Working Out", color: "#253858" },
    { value: "Eating", label: "Eating", color: "#666666" },
    { value: "Partying", label: "Partying", color: "#36B37E" },
    { value: "Cooking", label: "Cooking", color: "#FF8B00" },
    { value: "Movies", label: "Food", color: "#0052CC" },
    { value: "Bird Watching", label: "Bird Watching", color: "#00B8D9" },
    { value: "Gaming", label: "Gaming", color: "#00875A" },
    { value: "Shopping", label: "Shopping", color: "#5243AA" },
    { value: "Chess", label: "Chess", color: "#FF5630" },
    { value: "HangingWithFriends", label: "Hnging with friends", color: "#253858" },
    { value: "Dancing", label: "Dancing", color: "#666666" },
    { value: "Traveling", label: "Traveling", color: "#36B37E" },
    { value: "DoingHackathons!", label: "Doing Hackathons!", color: "#FF8B00" },
  ];